// <auto-generated />
using System;
using BookStore.Shop.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookStore.Shop.Api.Migrations
{
    [DbContext(typeof(ContextShopping))]
    [Migration("20211119232509_MigrationMySQLInicial")]
    partial class MigrationMySQLInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("BookStore.Shop.Api.Models.ShoppingDetail", b =>
                {
                    b.Property<int>("ShoppingSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SelectedProduct")
                        .HasColumnType("longtext");

                    b.Property<int>("ShoppingSesionId")
                        .HasColumnType("int");

                    b.Property<int?>("shoppingSessionShoppingSesionId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingSessionId");

                    b.HasIndex("shoppingSessionShoppingSesionId");

                    b.ToTable("ShoppingDetail");
                });

            modelBuilder.Entity("BookStore.Shop.Api.Models.ShoppingSession", b =>
                {
                    b.Property<int>("ShoppingSesionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ShoppingSesionId");

                    b.ToTable("ShoppingSession");
                });

            modelBuilder.Entity("BookStore.Shop.Api.Models.ShoppingDetail", b =>
                {
                    b.HasOne("BookStore.Shop.Api.Models.ShoppingSession", "shoppingSession")
                        .WithMany("shoppingDetails")
                        .HasForeignKey("shoppingSessionShoppingSesionId");

                    b.Navigation("shoppingSession");
                });

            modelBuilder.Entity("BookStore.Shop.Api.Models.ShoppingSession", b =>
                {
                    b.Navigation("shoppingDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
